plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.40'
    annotationProcessor 'org.projectlombok:lombok:1.18.40'
    testImplementation 'io.rest-assured:rest-assured:5.5.0'
    testImplementation 'io.cucumber:cucumber-java:7.15.0'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.22.1'
    testImplementation("com.codeborne:selenide:7.18.0")

    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.15.0'

    testImplementation 'org.junit.platform:junit-platform-suite-api:1.10.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-suite-engine:1.10.1'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'net.datafaker:datafaker:2.5.4'
    implementation 'com.github.lalyos:jfiglet:0.0.8'
}

test {
    useJUnitPlatform()
}